network: testnet
providers:
  - currency: BTC
    provider_type: BtcProvider
    service_url: https://mempool.space/signet
    derivation_path: m/44'/1'/0'/0
  - currency: ETH
    provider_type: EthProvider
    service_url: https://1rpc.io/sepolia
    derivation_path: m/44'/1'/0'/0
  - currency: USDC
    provider_type: EthTokenProvider
    service_url: https://1rpc.io/sepolia
    token_address: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    derivation_path: m/44'/1'/0'/0


